name: run testproject job
on: [push, pull_request]
jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Run a job
        uses: ./
        with:
          url: 'https://api.testproject.io/v2/projects/8AKvFLJScEmtFPelPYyopg/jobs/qTVvaDX3AEuX9uisw5q0Tw/run'
          method: 'POST'
          headers: "{'Authorization':mRPhq26xIkLrCIhZ1vL2RJI_BfUzO7o3ExUeTfzOKkI1}"
    


